name: Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  push_to_ecr:
    name: Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Replace with your AWS region

      - name: Login to Amazon ECR
        id: login-ecr
        run: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com
        

      - name: Build and tag Docker image
        run: |
          docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/my-repo:${GITHUB_SHA} .
          docker tag ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/my-repo:${GITHUB_SHA} ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/my-repo:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/my-repo:${GITHUB_SHA}
          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/my-repo:latest
